
management:
  endpoints.web.exposure.include: health,info,metrics,gateway
  endpoint.health.show-details: always
  endpoint.gateway.access: read-only
  prometheus.metrics.export.enabled: true
  info.env.enabled: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE

server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: shopping_store_service
              uri: lb://shopping-store
              predicates:
                - Path=/shopping-store/**
              filters:
                - StripPrefix=1
                - name: Retry
                  args:
                    retries: 2
                    statuses: NOT_FOUND
                    methods: GET
                    backoff:
                      firstBackoff: 10ms
                      maxBackoff: 50ms
                      factor: 2
                      basedOnPreviousValue: false

            - id: shopping_cart_service
              uri: lb://shopping-cart
              predicates:
                - Path=/shopping-cart/**
              filters:
                - StripPrefix=1

            - id: warehouse_service
              uri: lb://warehouse
              predicates:
                - Path=/warehouse/**
              filters:
                - StripPrefix=1