info:
  app:
    name: config-server
    description: Smart Home Tech Project
    version: 1.0-SNAPSHOT
  company:
    name: Yandex Practicum

management:
  endpoints.web.exposure.include: health,info,metrics
  endpoint.health.show-details: always
  metrics.export.prometheus.enabled: true
  info.env.enabled: true

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/telemetry/{application}
            - classpath:config/commerce/{application}

server:
  port: 0
  shutdown: graceful

logging:
  level:
    root: INFO

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false
    hostname: localhost