package ru.yandex.practicum.dto.order;

public enum OrderState {

    NEW,
    ASSEMBLY_FAILED,
    ASSEMBLED,
    CALCULATION_FAILED,
    CALCULATED,
    CREATE_PAYMENT_FAILED,
    ON_PAYMENT,
    PAYMENT_FAILED,
    PAID,
    CREATE_DELIVERY_FAILED,
    SENT_TO_DELIVERY,
    ON_DELIVERY,
    DELIVERY_FAILED,
    DELIVERED,
    PRODUCT_RETURNED,
    DONE,
    COMPLETED,
    CANCELED,
    WRITE_OFF_FAILED,
    RETURN_PRODUCTS,
    RETURNED,
    RETURN_FAILED

}