management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    topics:
      sensor-events: telemetry.sensors.v1
      hub-events: telemetry.hubs.v1