spring:
  grpc:
    server:
      port: 9090
      max-inbound-message-size: 8388608 # 8MB
      max-header-list-size: 65536 # 64KB

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    topics:
      sensor-events: telemetry.sensors.v1
      hub-events: telemetry.hubs.v1